https://investors.sgx.com/market/stock-screener?from=/market/securities

---

# Setup & Import

In [46]:
# Setup
%load_ext autoreload
%autoreload 2
#%load_ext jupyter_ai_magics
import sys; sys.path.append('..')
from src.env_setup import init_analysis_env; init_analysis_env()

df_ = load_local_data("Stock Screener Data*.csv*", na_values=['-'], dtype={'Code': str})
df_.head()

# Cleaning

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
🚀 Analysis environment initialized: pd, np, yf, plt, sns, load_local_data, datetime, timedelta, xw are ready.
Loading: /home/mrsmmori/notebooks/Win_Downloads/Stock Screener Data 7 Jun 11-8-22.csv.csv

,Trading Name,Code,Last Price,ROE %,Mkt Cap ($M),Tot. Rev ($M),P/E,Yield (%),Sector,GTI Score,4-wk %Pr. Chg.,13-wk %Pr. Chg.,26-wk %Pr. Chg.,52-wk %Pr. Chg.,Net Profit,Price/CF,Debt/Equity,1-yr %Rev. Chg.,Price/Book Value
0,Tai Sin Electric,500,0.55,12.09,SGD 250.843,SGD 527.837,14.30,4.31,Industrials,78.00,-5.22,5.24,-5.56,38.66,0.05,NaN,0.04,19.98,1.12
1,HS Optimus,504,0.01,5.73,SGD 37.664,SGD 13.551,13.73,NaN,Consumer Cyclical,67.00,0.00,133.33,250.00,250.00,0.20,74.07,0.01,-6.18,0.77
2,AsiaMedic,505,0.02,13.34,SGD 26.4,SGD 35.221,13.14,NaN,Healthcare,66.00,0.00,21.05,21.05,91.67,0.03,6.85,0.96,21.81,1.64
3,Fuji Offset,508,0.73,2.33,SGD 43.736,SGD 3.274,48.34,0.68,Industrials,70.00,28.95,5.76,36.11,-10.91,0.28,357.14,0.00,-9.76,1.14
4,DISA,532,0.00,-137.72,SGD 14.09,SGD 2.667,NaN,NaN,Technology,34.00,0.00,0.00,0.00,0.00,-0.42,NaN,0.01,-19.20,3.67

In [47]:
def make_clickable(val):
    if pd.notna(val):
        return f'<a target="_blank" href="{val}">Link to SGX</a>'
    return ""

# Data Clearning

In [48]:
df = df_.copy()

In [49]:
rename_dict = {
    'Trading Name':    'name',
    'Code':            'code',
    'Last Price':      'price',
    'ROE %':           'roe',
    'Mkt Cap ($M)':    'mkt_cap',
    'Tot. Rev ($M)':   'rev',
    'P/E':             'pe',
    'Yield (%)':       'yield',
    'Sector':          'sector',
    'GTI Score':       'gti',
    '4-wk %Pr. Chg.':  'chg_4w',
    '13-wk %Pr. Chg.': 'chg_13w',
    '26-wk %Pr. Chg.': 'chg_26w',
    '52-wk %Pr. Chg.': 'chg_52w',
    'Net Profit':      'net_profit',
    'Price/CF':        'p_cf',
    'Debt/Equity':     'de',
    '1-yr %Rev. Chg.': 'rev_chg_1y',
    'Price/Book Value':'pb'
}

df = df.rename(columns=rename_dict)

In [50]:
string_cols = ["name", "code", "sector"]
for col in string_cols:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip()

def clean_numeric(series):
    if series.dtype == "object":
        series = (
            series.astype(str)
            .str.replace(",", "", regex=False)
            .str.replace("%", "", regex=False)
            .str.replace("$", "", regex=False)
            .str.replace(" ", "", regex=False)
        )
        series = pd.to_numeric(series, errors="coerce")
    return series


numeric_cols = [
    "price",
    "roe",
    "mkt_cap",
    "rev",
    "pe",
    "yield",
    "gti",
    "chg_4w",
    "chg_13w",
    "chg_26w",
    "chg_52w",
    "net_profit",
    "p_cf",
    "de",
    "rev_chg_1y",
    "pb",
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = clean_numeric(df[col])

if "code" in df.columns:
    df = df.drop_duplicates(subset=["code"], keep="first")

print(df.dtypes)

name              str
code              str
price         float64
roe               str
mkt_cap           str
rev               str
pe            float64
yield         float64
sector            str
gti           float64
chg_4w        float64
chg_13w       float64
chg_26w       float64
chg_52w           str
net_profit    float64
p_cf          float64
de            float64
rev_chg_1y        str
pb            float64
dtype: object

In [51]:
list(df["sector"].unique())

['Industrials',
 'Consumer Cyclical',
 'Healthcare',
 'Technology',
 'Basic Materials',
 'Consumer Defensive',
 'Real Estate',
 'Energy',
 'Utilities',
 'Financial Services',
 nan,
 'Communication Services']

In [52]:
df.head(5)

,name,code,price,roe,mkt_cap,rev,pe,yield,sector,gti,chg_4w,chg_13w,chg_26w,chg_52w,net_profit,p_cf,de,rev_chg_1y,pb
0,Tai Sin Electric,500,0.55,12.09,SGD 250.843,SGD 527.837,14.30,4.31,Industrials,78.00,-5.22,5.24,-5.56,38.66,0.05,NaN,0.04,19.98,1.12
1,HS Optimus,504,0.01,5.73,SGD 37.664,SGD 13.551,13.73,NaN,Consumer Cyclical,67.00,0.00,133.33,250.00,250.00,0.20,74.07,0.01,-6.18,0.77
2,AsiaMedic,505,0.02,13.34,SGD 26.4,SGD 35.221,13.14,NaN,Healthcare,66.00,0.00,21.05,21.05,91.67,0.03,6.85,0.96,21.81,1.64
3,Fuji Offset,508,0.73,2.33,SGD 43.736,SGD 3.274,48.34,0.68,Industrials,70.00,28.95,5.76,36.11,-10.91,0.28,357.14,0.00,-9.76,1.14
4,DISA,532,0.00,-137.72,SGD 14.09,SGD 2.667,NaN,NaN,Technology,34.00,0.00,0.00,0.00,0.00,-0.42,NaN,0.01,-19.20,3.67

In [53]:
def clean_currency_to_float(series):
    cleaned = (
        series.astype(str)
        .str.replace("SGD", "", regex=False)
        .str.replace(" ", "", regex=False)
        .str.replace(",", "", regex=False)
    )
    return pd.to_numeric(cleaned, errors="coerce")


# 'mkt_cap' と 'rev' を両方とも数値型（float）に変換
df["mkt_cap"] = clean_currency_to_float(df["mkt_cap"])
df["rev"] = clean_currency_to_float(df["rev"])

In [54]:
df.head(5)

,name,code,price,roe,mkt_cap,rev,pe,yield,sector,gti,chg_4w,chg_13w,chg_26w,chg_52w,net_profit,p_cf,de,rev_chg_1y,pb
0,Tai Sin Electric,500,0.55,12.09,250.84,527.84,14.30,4.31,Industrials,78.00,-5.22,5.24,-5.56,38.66,0.05,NaN,0.04,19.98,1.12
1,HS Optimus,504,0.01,5.73,37.66,13.55,13.73,NaN,Consumer Cyclical,67.00,0.00,133.33,250.00,250.00,0.20,74.07,0.01,-6.18,0.77
2,AsiaMedic,505,0.02,13.34,26.40,35.22,13.14,NaN,Healthcare,66.00,0.00,21.05,21.05,91.67,0.03,6.85,0.96,21.81,1.64
3,Fuji Offset,508,0.73,2.33,43.74,3.27,48.34,0.68,Industrials,70.00,28.95,5.76,36.11,-10.91,0.28,357.14,0.00,-9.76,1.14
4,DISA,532,0.00,-137.72,14.09,2.67,NaN,NaN,Technology,34.00,0.00,0.00,0.00,0.00,-0.42,NaN,0.01,-19.20,3.67

In [55]:
df['SGX_URL'] = np.nan
mask = df['code'].notna()
df['SGX_URL'] = df['code'].apply(
    lambda x: f'https://investors.sgx.com/market/security-details/stocks/{x}' if pd.notna(x) else None
)

In [56]:
cols = list(df.columns)
cols.remove('SGX_URL') 
cols.insert(2, 'SGX_URL') 
df = df[cols]

In [57]:
# 極限まで短くしたい場合のマッピング定義
short_mapping = {
    "Industrials": "ind",
    "Consumer Cyclical": "cyclical",
    "Healthcare": "health",
    "Technology": "tech",
    "Basic Materials": "materials",
    "Consumer Defensive": "defensive",
    "Real Estate": "estate",
    "Energy": "energy",
    "Utilities": "utilities",
    "Financial Services": "finance",
    "Communication Services": "comm",
}

sector_dfs = {}
for sector in df["sector"].unique():
    if pd.isna(sector):
        continue

    # マッピングにあればそれを使い、なければ小文字変換にする
    short_name = short_mapping.get(sector, str(sector).lower().replace(" ", "_"))

    sector_dfs[short_name] = df[df["sector"] == sector].copy()

## Industrial

In [58]:
sector_dfs['ind'].sort_values(by="rev", ascending=False, na_position="last").head(5).style.format({'SGX_URL': make_clickable})

1. 【高ROE・高配当】圧倒的な勢いと罠を併せ持つ「造船最大手」
Yangzijiang Shipbuilding (BS6 / YZJ Shipbldg)

データの特徴: ROE 29.57% という驚異的な収益性を誇り、配当利回りも 5.65% と高水準。PE（PER）は 8.52倍 と極めて割安に見えます。

背景と現状: 世界的なコンテナ船・環境対応船の需要爆発を背景に、手持ち工事残高（バックログ）が過去最高水準に達しており、純利益成長率（net_profit）も0.29（+29%）と絶好調です。

投資判断: 直近4週間（-13.43%）、13週間（-11.37%）と、株価は大きく調整を入れています。これは3月に過去最高値（4.29 SGD）をつけた後の利益確定売りの動きです。ファンダメンタルズ（企業の稼ぐ力）は崩れておらず、このセクターで「高い配当と成長」を同時に狙うなら、今回の調整局面は絶好のエントリーチャンスと言えます。

## "Consumer Cyclical": "cyclical",

In [59]:
sector_dfs['cyclical'].sort_values(by="rev", ascending=False, na_position="last").head(5).style.format({'SGX_URL': make_clickable})

## "Healthcare": "health",

In [60]:

sector_dfs['health'].sort_values(by="rev", ascending=False, na_position="last").head(10).style.format({'SGX_URL': make_clickable})

## "Technology": "tech",

In [61]:
sector_dfs['tech'].sort_values(by="rev", ascending=False, na_position="last").head(10).style.format({'SGX_URL': make_clickable})

1. 【AI・グラボ特需】驚異的なリターンを叩き出す「本命・成長株」
グラフィックボード（GPU）の製造や、最先端の半導体・AI関連インフラに直結している、今まさに市場の資金を集めているグループです。
PC Partner Group (PCT)
分析: 自社ブランド（ZOTACなど）でNVIDIAなどのGPU（グラフィックボード）を製造・販売する企業です。ROE 16.31% と高く、52週間（1年間）の株価パフォーマンスは +105.26% と驚異的な大化けを演じています。
配当視点: 急騰した後でも 配当利回りは 4.10%、PE（PER）も 10.77倍 と、業績の伸びに対して依然として割安感を残しています。AIやゲーミング需要の恩恵をダイレクトに受けながら4%超のインカムを得られる、現在のSGXテックセクターの主役と言えます。
Frencken Group (E28)

分析: 半導体製造装置や医療機器の精密コンポーネントを手掛ける企業。52週間で +154.09%、直近13週間（約3ヶ月）だけでも +45.20% と猛烈に買われています。

注意点: 利回りは 0.94% と低く、期待先行でPEが 31.91倍 まで買われているため、配当目的の投資としては向きません。キャピタルゲイン（値上がり益）狙いの銘柄です。

## "Basic Materials": "materials",

In [62]:
sector_dfs['materials'].sort_values(by="rev", ascending=False, na_position="last").head(10).style.format({'SGX_URL': make_clickable})

## "Consumer Defensive": "defensive",

In [63]:
sector_dfs['defensive'].sort_values(by="rev", ascending=False, na_position="last").head(10).style.format({'SGX_URL': make_clickable})

## "Real Estate": "estate",

In [64]:
sector_dfs['estate'].sort_values(by="rev", ascending=False, na_position="last").head(10).style.format({'SGX_URL': make_clickable})

## "Energy": "energy",

In [65]:
sector_dfs['energy'].sort_values(by="rev", ascending=False, na_position="last").head(10).style.format({'SGX_URL': make_clickable})

## "Utilities": "utilities",

In [66]:
sector_dfs['utilities'].sort_values(by="rev", ascending=False, na_position="last").head(10).style.format({'SGX_URL': make_clickable})

Sembcorp Industries（U96）について、なぜこれほど強力な業績（ROE 17.92%）を持ちながらPE（PER）が11倍前後という「割安」な水準で放置されているのか、その理由を構造と背景から紐解きます。
1. なぜPEが11倍なのか？（4つの理由）
一般的にROEが15%を超えるような高収益企業は、期待値からPEが20〜30倍に買われることも珍しくありません。しかし、U96が11倍にとどまるのは以下のセクター固有の事情とマクロ環境が影響しています。

① 「資本集約型」の重厚長大ビジネスであるため
U96の主力は発電所やエネルギーインフラの建設・運営です。これらは巨額の設備投資（CapEx）を必要とし、借入金も多くなる（DE倍率も高めになる）ため、市場からはテクノロジー株のような「身軽な高成長株」としては評価されず、伝統的な「バリュー株・ユーティリティ株」の枠組み（PE10〜13倍が適正水準）でプライシングされます。

② シンガポール国内での電力卸売価格（スパークスプレッド）の頭打ち懸念
ここ数年、シンガポール国内の電力需給の逼迫から同社の電力事業は莫大な利益を上げてきましたが、市場は「この高い利益率は一時的なピークであり、今後は価格競争や供給増加によって緩やかに正常化（低下）していくのではないか」という警戒感を持っています。将来の利益減少を織り込むため、足元のPEは低く出やすくなります。

③ 「茶色（化石燃料）から緑（再生可能エネルギー）」への過渡期リスク
U96は現在、従来のガス発電（Brown）から、太陽光や風力などの再生可能エネルギー（Green）へ事業構造を大転換している真っ最中です。

2028年までに再エネ容量を25GWまで拡大する野心的な目標を掲げ、直近（2026年6月）にもオーストラリアのAlinta Energyの買収を完了させるなど猛スピードで動いています。

しかし、再エネは初期投資が重く、中国など一部地域での売電タラフ（価格制度）の不確実性もあるため、市場は「本当に計画通りの利益率を維持できるか」を慎重に見極めており、これが株価の重し（割安放置）に繋がっています。

④ 地理的リスク（新興国ビジネスの不確実性）
同社の再エネやインフラ事業はシンガポール国内だけでなく、中国、インド、ベトナム、インドネシアなど多岐にわたります。これらの新興国ビジネスは成長性が高い反面、規制変更や為替リスク、現地の電力網（グリッド）の制約といった不確実性を伴うため、シンガポール拠点の純粋なディフェンシブ株に比べてリスクプレミアム（ディスカウント）が要求されます。

## "Financial Services": "finance",

In [67]:
sector_dfs['finance'].sort_values(by="rev", ascending=False, na_position="last").head(10).style.format({'SGX_URL': make_clickable})

## "Communication Services": "comm",

In [68]:
sector_dfs['comm'].sort_values(by="rev", ascending=False, na_position="last").head(10).style.format({'SGX_URL': make_clickable})