https://www.sgx.com/securities/etf-screener

# Setup

In [1]:
# Setup
%load_ext autoreload
%autoreload 2
#%load_ext jupyter_ai_magics
import sys; sys.path.append('..')
from src.env_setup import init_analysis_env; init_analysis_env()


df = load_local_data("myData*.csv*", na_values=['-'], dtype={'Code': str})
df.head()

# Cleaning

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
🚀 Analysis environment initialized: pd, np, yf, plt, sns, load_local_data, datetime, timedelta, xw are ready.
Loading: /home/mrsmmori/notebooks/Win_Downloads/myData.csv

,Trading Name,Trading Code,CCY,Underlying Benchmark,Close,Last,Chng %,Val ($M),Yield (%),TER (%),...,Ann. TR 1Y (%),Ann. TR 3Y (%),Asset Class,Geographical Focus,Income Treatment,Sustainability linked,Management Style,CPF Eligibility,SIP/EIP,Tick Size
0,STI ETF,ES3,SGD,Straits Times Index,4.41,4.41,0.14,5.87,4.17,0.28,...,30.48,14.80,Equities,Singapore,Distributing,No,PASSIVE,Yes,EIP,0.00
1,IS ASIA HYG US$,O9P,USD,Bloomberg Asia USD High Yield Diversified Cred...,6.70,6.70,0.30,4.54,7.23,0.50,...,7.16,8.99,Fixed Income,Asia,Distributing,No,PASSIVE,No,EIP,0.01
2,GLD US$,O87,USD,LBMA Gold Price PM,340.00,340.00,1.52,4.10,NaN,0.40,...,35.65,24.62,Commodities,Gold,NaN,No,PASSIVE,Yes,EIP,0.01
3,Lion-OCBC Sec HSTECH S$,HST,SGD,Hang Seng TECH Index,0.96,0.96,1.26,4.09,NaN,0.58,...,61.74,7.35,Equities,China,Accumulating,No,PASSIVE,No,EIP,0.00
4,LION-PHILLIP S-REIT,CLR,SGD,Morningstar Singapore REIT Yield Focus Index SM,0.86,0.86,0.93,2.97,5.67,0.60,...,-0.23,-1.81,REITs,Singapore,Distributing,No,PASSIVE,No,EIP,0.00

In [2]:
target_columns = [
    "Yield (%)",
    "TR 1M (%)",
    "TR 3M (%)",
    "TR 1Y (%)",
    "Ann. TR 1Y (%)",
    "Ann. TR 3Y (%)",
]

df[target_columns] = df[target_columns].round(2)

In [3]:
df["Geographical Focus"].value_counts()

Geographical Focus
China               29
Singapore           17
Asia                15
Asia Pacific         8
India                3
Vietnam              3
Gold                 2
USA                  2
Japan                2
Saudi Arabia         1
Indonesia            1
Emerging Markets     1
Name: count, dtype: int64

# df -> df_usd, df_sgd

In [4]:
df_usd = df[(df["CCY"] == "USD") | (df["CCY"] == "USD")].copy()
df_sgd = df[(df["CCY"] == "SGD") | (df["CCY"] == "SGD")].copy()

# df_sgd -> df

In [5]:
df = df_sgd.copy()
df = df[df["Sustainability linked"] == "No"]

In [6]:
df["Geographical Focus"].value_counts()

Geographical Focus
China           13
Singapore        9
Asia             6
Asia Pacific     2
Gold             1
Japan            1
Vietnam          1
Name: count, dtype: int64

In [7]:
df["Asset Class"].value_counts()

Asset Class
Equities        20
Fixed Income     8
REITs            4
Commodities      1
Name: count, dtype: int64

In [8]:
df["Income Treatment"].value_counts()

Income Treatment
Distributing    20
Accumulating    12
Name: count, dtype: int64

Distributing（分配型）
→ ファンドが得た配当や利息を投資家に分配します。
→ 例：ETFが四半期ごとに配当金を支払う。

Accumulating（再投資型）
→ ファンドが得た配当や利息を投資家に分配せず、ファンド内部で自動的に再投資します。
→ その結果、投資家の受け取るキャッシュはないけど、基準価額（NAV）が上昇していきます。

In [9]:
base_url = "https://investors.sgx.com/market/securities?code="
last_url = "&type=etfs&lang=en"
df['URL'] = base_url + df['Trading Code'] + last_url

In [10]:
df = df[
    [
        "Trading Name",
        "Trading Code",
        #'CCY',
        "Underlying Benchmark",
        "URL",
        #'Close',
        #'Last',
        #'Chng %',
        #'Val ($M)',
        "Yield (%)",
        #'TER (%)',
        #'Documents',
        #'Fund Manager',
        "TR 1M (%)",
        "TR 3M (%)",
        "TR 1Y (%)",
        "Ann. TR 1Y (%)",
        "Ann. TR 3Y (%)",
        "Asset Class",
        "Geographical Focus",
        "Income Treatment",
        #'Sustainability linked',
        "Management Style",
        #'CPF Eligibility',
        #'SIP/EIP',
        #'Tick Size',
    ]
]

In [11]:
pd.crosstab(df["Asset Class"], df["Income Treatment"])

Income Treatment  Accumulating  Distributing
Asset Class
Equities                    11             9
Fixed Income                 1             7
REITs                        0             4

In [12]:
df_bonds = df.query("`Asset Class` == 'BONDS'")
df_bonds.style.format({'URL': lambda x: f'<a target="_blank" href="{x}">link</a>'})

In [13]:
df_equities = df.query("`Asset Class`.str.lower() == 'equities'")
df_equities.style.format({'URL': lambda x: f'<a target="_blank" href="{x}">link</a>'})

In [14]:
df_reits = df.query("`Asset Class` == 'REITs'")
df_reits.style.format({'URL': lambda x: f'<a target="_blank" href="{x}">link</a>'})

In [15]:
#df.style.format({'URL': lambda x: f'<a target="_blank" href="{x}">link</a>'})

In [16]:
code = "VND"
url = f"https://www.example.com/stocks/{code}"
print(url)

https://www.example.com/stocks/VND

# df_usd -> df

In [17]:
df = df_usd.copy()
df = df[df["Sustainability linked"] == "No"]

In [18]:
grouped = df.groupby(["Asset Class", "Income Treatment"])

for (asset_class, income), group_df in grouped:
    print(f"=== Asset Class: {asset_class}, Income Treatment: {income} ===")
    group_df

=== Asset Class: Equities, Income Treatment: Accumulating ===

,Trading Name,Trading Code,CCY,Underlying Benchmark,Close,Last,Chng %,Val ($M),Yield (%),TER (%),...,Ann. TR 1Y (%),Ann. TR 3Y (%),Asset Class,Geographical Focus,Income Treatment,Sustainability linked,Management Style,CPF Eligibility,SIP/EIP,Tick Size
28,XT MSCHINA US$,LG9,USD,MSCI China TR Net Daily USD Index,21.00,21.00,1.79,0.03,NaN,0.65,...,47.90,8.73,Equities,China,Accumulating,No,PASSIVE,No,EIP,0.01
31,CF VN 30 SC ETF US$,VND,USD,iEdge Vietnam 30 Sector Cap USD Index (NTR),1.28,1.26,2.52,0.03,NaN,2.39,...,50.79,NaN,Equities,Vietnam,Accumulating,No,PASSIVE,No,EIP,0.00
38,Amundi MSIndia Sw US$,G1N,USD,MSCI India Net Total Return Index,32.10,32.23,0.41,0.00,NaN,0.85,...,-11.87,7.62,Equities,India,Accumulating,No,PASSIVE,No,SIP,0.01
41,XT MSINDO US$,KJ7,USD,MSCI Daily TRN Net Emerging Markets Indonesia ...,13.47,13.18,1.39,0.00,NaN,0.65,...,-16.77,-4.46,Equities,Indonesia,Accumulating,No,PASSIVE,No,SIP,0.01
46,XT Vietnam US$,HD9,USD,FTSE Vietnam Index,37.67,37.61,1.65,0.00,NaN,0.85,...,43.57,2.79,Equities,Vietnam,Accumulating,No,PASSIVE,No,SIP,0.01
49,A Lion-Nomura Japan US$,JUS,USD,Topix Index,0.97,0.97,0.00,0.00,NaN,0.98,...,30.13,NaN,Equities,Japan,Accumulating,No,ACTIVE,No,EIP,0.00
50,Amova Asia exJC US$,A94,USD,MSCI AC Asia ex Japan ex China Index,0.89,0.86,0.00,0.00,NaN,NaN,...,NaN,NaN,Equities,Asia,Accumulating,No,PASSIVE,No,EIP,0.00
57,AmovaEFund ChiNext US$,CXO,USD,ChiNext Index,0.19,0.00,0.00,0.00,NaN,NaN,...,NaN,NaN,Equities,China,Accumulating,No,PASSIVE,No,EIP,0.00
58,Amundi EM Mkt Sw US$,H1N,USD,MSCI Emerging Market Net Total Return Index,16.67,16.25,0.00,0.00,NaN,0.55,...,17.18,10.54,Equities,Emerging Markets,Accumulating,No,PASSIVE,No,SIP,0.01
63,CSOP SEA TECH ETF US$,SQU,USD,iEdge Southeast Asia+ TECH Index,0.96,0.93,0.00,0.00,NaN,1.41,...,13.89,NaN,Equities,Asia,Accumulating,No,PASSIVE,No,EIP,0.00
70,Lion-CM EM Asia US$,EAU,USD,iEdge Emerging Asia Select 50 Index,0.96,0.95,0.00,0.00,NaN,NaN,...,NaN,NaN,Equities,Asia,Accumulating,No,PASSIVE,No,EIP,0.00
71,Lion-OCBC Sec HSTECH US$,HSS,USD,Hang Seng TECH Index,0.75,0.74,0.00,0.00,NaN,0.58,...,63.66,10.44,Equities,China,Accumulating,No,PASSIVE,No,EIP,0.00
75,PHIL SING INC USD,OVS,USD,Morningstar Singapore Yield Focus Index,1.13,1.10,0.00,0.00,NaN,NaN,...,NaN,NaN,Equities,Singapore,Accumulating,No,PASSIVE,No,EIP,0.00
77,PHIL-CU MS CHINA A50 US$,MCS,USD,MSCI China A 50 Connect Index,1.04,0.85,0.00,0.00,NaN,1.10,...,16.03,NaN,Equities,China,Accumulating,No,PASSIVE,No,EIP,0.00
82,UOBAM PINGAN CHINEXT US$,CXU,USD,ChiNext Index,0.83,0.80,0.00,0.00,NaN,1.39,...,76.65,NaN,Equities,China,Accumulating,No,PASSIVE,No,EIP,0.00
83,XT MS SING US$,O9A,USD,MSCI Singapore Investable Market Total Return ...,2.33,2.33,0.00,0.00,NaN,0.50,...,40.85,19.33,Equities,Singapore,Accumulating,No,PASSIVE,No,EIP,0.00

=== Asset Class: Equities, Income Treatment: Distributing ===

,Trading Name,Trading Code,CCY,Underlying Benchmark,Close,Last,Chng %,Val ($M),Yield (%),TER (%),...,Ann. TR 1Y (%),Ann. TR 3Y (%),Asset Class,Geographical Focus,Income Treatment,Sustainability linked,Management Style,CPF Eligibility,SIP/EIP,Tick Size
20,SPDR S&P500 US$,S27,USD,S&P 500 Index,658.05,658.04,0.62,0.10,1.20,0.00,...,16.95,18.67,Equities,USA,Distributing,No,PASSIVE,No,SIP,0.01
40,Lion-OSPL APAC Fin US$,YLU,USD,iEdge APAC Financials Dividend Plus Index,0.99,0.99,3.22,0.00,6.44,1.08,...,44.26,NaN,Equities,Asia Pacific,Distributing,No,PASSIVE,No,EIP,0.00
60,CGS FG CSI1000 US$,GRU,USD,CSI 1000 Index,1.22,1.22,0.00,0.00,NaN,1.96,...,45.19,NaN,Equities,China,Distributing,No,PASSIVE,No,EIP,0.00
79,SPDR DJIA US$,D07,USD,Dow Jones Industrial AverageSM (DJIASM) Index,462.13,459.00,0.00,0.00,1.49,0.16,...,11.95,14.43,Equities,USA,Distributing,No,PASSIVE,No,SIP,0.01
81,UOBAM FTSE CN A50 US$,VK8,USD,FTSE China A50 Index,1.89,1.64,0.00,0.00,NaN,0.84,...,NaN,NaN,Equities,China,Distributing,No,PASSIVE,No,EIP,0.00

=== Asset Class: Fixed Income, Income Treatment: Accumulating ===

,Trading Name,Trading Code,CCY,Underlying Benchmark,Close,Last,Chng %,Val ($M),Yield (%),TER (%),...,Ann. TR 1Y (%),Ann. TR 3Y (%),Asset Class,Geographical Focus,Income Treatment,Sustainability linked,Management Style,CPF Eligibility,SIP/EIP,Tick Size
36,SPDR JPM SaudiAggBd US$,KSB,USD,J.P. Morgan Saudi Arabia Aggregate Index,31.46,31.39,0.93,0.01,NaN,0.37,...,NaN,NaN,Fixed Income,Saudi Arabia,Accumulating,No,PASSIVE,No,EIP,0.00
53,Amova-ICBCSG CNB US$,ZHD,USD,ChinaBond ICBC 1-10 Year Treasury and Policy B...,0.84,0.83,0.00,0.00,NaN,0.30,...,NaN,NaN,Fixed Income,China,Accumulating,No,PASSIVE,No,EIP,0.00
64,ICBC CSOP CGB ETF US$A,CYX,USD,FTSE Chinese Government Bond Index,11.02,10.82,0.00,0.00,NaN,0.26,...,2.80,NaN,Fixed Income,China,Accumulating,No,PASSIVE,No,EIP,0.01

=== Asset Class: Fixed Income, Income Treatment: Distributing ===

,Trading Name,Trading Code,CCY,Underlying Benchmark,Close,Last,Chng %,Val ($M),Yield (%),TER (%),...,Ann. TR 1Y (%),Ann. TR 3Y (%),Asset Class,Geographical Focus,Income Treatment,Sustainability linked,Management Style,CPF Eligibility,SIP/EIP,Tick Size
1,IS ASIA HYG US$,O9P,USD,Bloomberg Asia USD High Yield Diversified Cred...,6.70,6.70,0.30,4.54,7.23,0.50,...,7.16,8.99,Fixed Income,Asia,Distributing,No,PASSIVE,No,EIP,0.01
65,ICBC CSOP CGB ETF US$D,CYB,USD,FTSE Chinese Government Bond Index,10.06,10.05,0.00,0.00,2.95,0.26,...,3.29,3.07,Fixed Income,China,Distributing,No,PASSIVE,No,EIP,0.01
66,IS ASIA BND US$,N6M,USD,J.P. Morgan Asia Credit Index - Core,9.91,9.90,0.00,0.00,4.24,0.20,...,3.65,5.80,Fixed Income,Asia,Distributing,No,PASSIVE,No,EIP,0.01
78,PHILLIP MM US$D,MMT,USD,FTSE SGD 3-month SOR Index,80.61,79.76,0.00,0.00,2.88,0.28,...,NaN,NaN,Fixed Income,Singapore,Distributing,No,PASSIVE,No,EIP,0.00

=== Asset Class: REITs, Income Treatment: Distributing ===

,Trading Name,Trading Code,CCY,Underlying Benchmark,Close,Last,Chng %,Val ($M),Yield (%),TER (%),...,Ann. TR 1Y (%),Ann. TR 3Y (%),Asset Class,Geographical Focus,Income Treatment,Sustainability linked,Management Style,CPF Eligibility,SIP/EIP,Tick Size
43,CSOP iEdge SREIT ETF US$,SRU,USD,iEdge SREIT Leaders Index,0.61,0.61,0.66,0.00,5.73,0.60,...,3.78,2.29,REITs,Singapore,Distributing,No,PASSIVE,No,EIP,0.00
54,Amova-STC A_REIT US$,COI,USD,FTSE EPRA/NAREIT Asia ex Japan Net Total Retur...,0.66,0.65,0.00,0.00,5.45,0.55,...,NaN,NaN,REITs,Asia,Distributing,No,PASSIVE,Yes,EIP,0.00
74,PHIL AP DIV REIT US$,BYI,USD,iEdge APAC ex Japan Dividend Leaders REIT Index,0.94,0.93,0.00,0.00,4.28,1.54,...,6.96,1.65,REITs,Asia Pacific,Distributing,No,PASSIVE,No,EIP,0.00

In [19]:
base_url = "https://investors.sgx.com/market/securities?code="
last_url = "&type=etfs&lang=en"
df['URL'] = base_url + df['Trading Code'] + last_url
df.style.format({'URL': lambda x: f'<a target="_blank" href="{x}">link</a>'})